# Generated by Django 5.2.5 on 2025-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_field', models.JSONField()),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'db_table': 'inputs',
            },
        ),
    ]
